#!/bin/csh -f

# Universal params
sampmode MCDS 8
coadd 1

## Wide Camera ##
camera wide

# Y band
obj Wide_YBand_Flat
filt y
tint 12
goi 5

# J band
obj Wide_JBand_Flat
filt j
tint 2
goi 5

# H band
obj Wide_HBand_Flat
filt h
tint 2
goi 5

# K band
obj Wide_HBand_Flat
filt k
tint 6
goi 5

## Narrow Camera ##
camera narrow

# J band
obj Narrow_JBand_Flat
filt j
tint 20
goi 5
