#!/bin/csh -f

camera wide
sampmode MCDS 8

# Y band
obj FS_32_YBand_Widefield
filt y
tint 0.75
coadd 2
bxy3 5
goi

# J band
obj FS_32_JBand_Widefield
filt j
tint 0.75
coadd 2
bxy3 5
goi

# H band
obj FS_32_HBand_Widefield
filt h
tint 0.75
coadd 2
bxy3 5
goi

# K band
obj FS_32_KBand_Widefield
filt k
tint 1.25
coadd 2
bxy3 5
goi
